### ISSUE TITLE
AttributeError when running extract_intron_gff3_from_gff3.py

### ISSUE THREAD

**Issue by KristinaGagalova** [irusri/Extract-intron-from-gff3#3]
Hi
I am having the following error:

```
python extract_intron_gff3_from_gff3.py genome.gff genome_introns.gff
Adding introns to GFF...
  - Input: genome.gff
  - Output: genome_introns.gff_introns.gff3
Through 0 genes...
Through 5000 genes...
Through 10000 genes...
Through 15000 genes...
Through 20000 genes...
Loaded 24072 genes
Traceback (most recent call last):
  File "extract_intron_gff3_from_gff3.py", line 114, in <module>
    instert_introns_to_gff3(file, store)
  File "extract_intron_gff3_from_gff3.py", line 25, in instert_introns_to_gff3
    gff_out.write(gene_rec)
  File "/home/kgagalova/anaconda2/lib/python2.7/site-packages/misopy/gff_utils.py", line 883, in write
    self._record_writer(rec)
  File "/home/kgagalova/anaconda2/lib/python2.7/site-packages/misopy/gff_utils.py", line 918, in _write_rec_v3
    fields = [_seqid_pat.sub(url_quote, rec.seqid),
  File "/home/kgagalova/anaconda2/lib/python2.7/urllib.py", line 1296, in quote
    if not s.rstrip(safe):
AttributeError: '_sre.SRE_Match' object has no attribute 'rstrip'
```

any hints on what this error could be?
Thank you in advance
Kristina

**Comment by irusri** [comment]
Hi
Sorry or the late reply. Do you have correct format of gff3 file? it seems something wrong with the source gff3 file.
Kind regards
Chanaka
